### ISSUE TITLE
Charts are not stable

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/watchmarket#43]
We need to provide a caching solution with validation for charts. Currently, it is not working stable and I need to redeploy container several times per day to make it work. Maybe there is an issue in fetching there - we need more research. (Maybe fixer API have limits)

**Comment by arein** [comment]
Sounds pretty bad. Few questions:
1. How did you root cause the reason to redeploy to be charts?
2. Can you use logs to confirm the fetching hypothesis? I think #44 should help to handle this better and diagnose this better
3. Curious: is there a historic reason for why charts are currently not stored

**Comment by EnoRage** [comment]
1) If charts response will be failed
2) Does not help at all
3) It was implemented, however it caches any string - so basically it caches errors as well as valid response
